/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutFailedRouteImport } from './routes/checkout.failed'
import { Route as AppPropertiesRouteImport } from './routes/app.properties'
import { Route as AppTenanciesIndexRouteImport } from './routes/app.tenancies.index'
import { Route as AppPropertiesIndexRouteImport } from './routes/app.properties.index'
import { Route as AppInvoicesIndexRouteImport } from './routes/app.invoices.index'
import { Route as AppContactsIndexRouteImport } from './routes/app.contacts.index'
import { Route as AppPropertiesNewRouteImport } from './routes/app.properties.new'
import { Route as AppPropertiesIdRouteImport } from './routes/app.properties.$id'
import { Route as AppPropertiesIdEditRouteImport } from './routes/app.properties.$id.edit'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutFailedRoute = CheckoutFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => CheckoutRoute,
} as any)
const AppPropertiesRoute = AppPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AppRoute,
} as any)
const AppTenanciesIndexRoute = AppTenanciesIndexRouteImport.update({
  id: '/tenancies/',
  path: '/tenancies/',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesIndexRoute = AppPropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPropertiesRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesNewRoute = AppPropertiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPropertiesRoute,
} as any)
const AppPropertiesIdRoute = AppPropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPropertiesRoute,
} as any)
const AppPropertiesIdEditRoute = AppPropertiesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppPropertiesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/app/': typeof AppIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/app/properties/$id': typeof AppPropertiesIdRouteWithChildren
  '/app/properties/new': typeof AppPropertiesNewRoute
  '/app/contacts/': typeof AppContactsIndexRoute
  '/app/invoices/': typeof AppInvoicesIndexRoute
  '/app/properties/': typeof AppPropertiesIndexRoute
  '/app/tenancies/': typeof AppTenanciesIndexRoute
  '/app/properties/$id/edit': typeof AppPropertiesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/app': typeof AppIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/app/properties/$id': typeof AppPropertiesIdRouteWithChildren
  '/app/properties/new': typeof AppPropertiesNewRoute
  '/app/contacts': typeof AppContactsIndexRoute
  '/app/invoices': typeof AppInvoicesIndexRoute
  '/app/properties': typeof AppPropertiesIndexRoute
  '/app/tenancies': typeof AppTenanciesIndexRoute
  '/app/properties/$id/edit': typeof AppPropertiesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/app/': typeof AppIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/app/properties/$id': typeof AppPropertiesIdRouteWithChildren
  '/app/properties/new': typeof AppPropertiesNewRoute
  '/app/contacts/': typeof AppContactsIndexRoute
  '/app/invoices/': typeof AppInvoicesIndexRoute
  '/app/properties/': typeof AppPropertiesIndexRoute
  '/app/tenancies/': typeof AppTenanciesIndexRoute
  '/app/properties/$id/edit': typeof AppPropertiesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/app/properties'
    | '/checkout/failed'
    | '/checkout/success'
    | '/app/'
    | '/checkout/'
    | '/app/properties/$id'
    | '/app/properties/new'
    | '/app/contacts/'
    | '/app/invoices/'
    | '/app/properties/'
    | '/app/tenancies/'
    | '/app/properties/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/checkout/failed'
    | '/checkout/success'
    | '/app'
    | '/checkout'
    | '/app/properties/$id'
    | '/app/properties/new'
    | '/app/contacts'
    | '/app/invoices'
    | '/app/properties'
    | '/app/tenancies'
    | '/app/properties/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/app/properties'
    | '/checkout/failed'
    | '/checkout/success'
    | '/app/'
    | '/checkout/'
    | '/app/properties/$id'
    | '/app/properties/new'
    | '/app/contacts/'
    | '/app/invoices/'
    | '/app/properties/'
    | '/app/tenancies/'
    | '/app/properties/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/failed': {
      id: '/checkout/failed'
      path: '/failed'
      fullPath: '/checkout/failed'
      preLoaderRoute: typeof CheckoutFailedRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/app/properties': {
      id: '/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AppPropertiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tenancies/': {
      id: '/app/tenancies/'
      path: '/tenancies'
      fullPath: '/app/tenancies/'
      preLoaderRoute: typeof AppTenanciesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties/': {
      id: '/app/properties/'
      path: '/'
      fullPath: '/app/properties/'
      preLoaderRoute: typeof AppPropertiesIndexRouteImport
      parentRoute: typeof AppPropertiesRoute
    }
    '/app/invoices/': {
      id: '/app/invoices/'
      path: '/invoices'
      fullPath: '/app/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contacts/': {
      id: '/app/contacts/'
      path: '/contacts'
      fullPath: '/app/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties/new': {
      id: '/app/properties/new'
      path: '/new'
      fullPath: '/app/properties/new'
      preLoaderRoute: typeof AppPropertiesNewRouteImport
      parentRoute: typeof AppPropertiesRoute
    }
    '/app/properties/$id': {
      id: '/app/properties/$id'
      path: '/$id'
      fullPath: '/app/properties/$id'
      preLoaderRoute: typeof AppPropertiesIdRouteImport
      parentRoute: typeof AppPropertiesRoute
    }
    '/app/properties/$id/edit': {
      id: '/app/properties/$id/edit'
      path: '/edit'
      fullPath: '/app/properties/$id/edit'
      preLoaderRoute: typeof AppPropertiesIdEditRouteImport
      parentRoute: typeof AppPropertiesIdRoute
    }
  }
}

interface AppPropertiesIdRouteChildren {
  AppPropertiesIdEditRoute: typeof AppPropertiesIdEditRoute
}

const AppPropertiesIdRouteChildren: AppPropertiesIdRouteChildren = {
  AppPropertiesIdEditRoute: AppPropertiesIdEditRoute,
}

const AppPropertiesIdRouteWithChildren = AppPropertiesIdRoute._addFileChildren(
  AppPropertiesIdRouteChildren,
)

interface AppPropertiesRouteChildren {
  AppPropertiesIdRoute: typeof AppPropertiesIdRouteWithChildren
  AppPropertiesNewRoute: typeof AppPropertiesNewRoute
  AppPropertiesIndexRoute: typeof AppPropertiesIndexRoute
}

const AppPropertiesRouteChildren: AppPropertiesRouteChildren = {
  AppPropertiesIdRoute: AppPropertiesIdRouteWithChildren,
  AppPropertiesNewRoute: AppPropertiesNewRoute,
  AppPropertiesIndexRoute: AppPropertiesIndexRoute,
}

const AppPropertiesRouteWithChildren = AppPropertiesRoute._addFileChildren(
  AppPropertiesRouteChildren,
)

interface AppRouteChildren {
  AppPropertiesRoute: typeof AppPropertiesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppTenanciesIndexRoute: typeof AppTenanciesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPropertiesRoute: AppPropertiesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppTenanciesIndexRoute: AppTenanciesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CheckoutRouteChildren {
  CheckoutFailedRoute: typeof CheckoutFailedRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutFailedRoute: CheckoutFailedRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
